# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='dob',
            new_name='bday',
        ),
    ]
